//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAENGSUNG_HNSMES_UI {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings_IDAT : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings_IDAT defaultInstance = ((Settings_IDAT)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings_IDAT())));
        
        public static Settings_IDAT Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string Scan_Comport {
            get {
                return ((string)(this["Scan_Comport"]));
            }
            set {
                this["Scan_Comport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public string Scan_BaudRate {
            get {
                return ((string)(this["Scan_BaudRate"]));
            }
            set {
                this["Scan_BaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string Scan_ParityBit {
            get {
                return ((string)(this["Scan_ParityBit"]));
            }
            set {
                this["Scan_ParityBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public string Scan_DataBit {
            get {
                return ((string)(this["Scan_DataBit"]));
            }
            set {
                this["Scan_DataBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Scan_Use {
            get {
                return ((bool)(this["Scan_Use"]));
            }
            set {
                this["Scan_Use"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM6")]
        public string Print_Comport {
            get {
                return ((string)(this["Print_Comport"]));
            }
            set {
                this["Print_Comport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public string Print_BaudRate {
            get {
                return ((string)(this["Print_BaudRate"]));
            }
            set {
                this["Print_BaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public string Print_DataBit {
            get {
                return ((string)(this["Print_DataBit"]));
            }
            set {
                this["Print_DataBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("One")]
        public string Print_StopBit {
            get {
                return ((string)(this["Print_StopBit"]));
            }
            set {
                this["Print_StopBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://218.158.2.71:8807/IDISYS_2012/IDAT_WebSvr.asmx")]
        public string WS_Address {
            get {
                return ((string)(this["WS_Address"]));
            }
            set {
                this["WS_Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Print_X {
            get {
                return ((string)(this["Print_X"]));
            }
            set {
                this["Print_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Print_Y {
            get {
                return ((string)(this["Print_Y"]));
            }
            set {
                this["Print_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Print_Use {
            get {
                return ((bool)(this["Print_Use"]));
            }
            set {
                this["Print_Use"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Login {
            get {
                return ((string)(this["Login"]));
            }
            set {
                this["Login"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KOREAN")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Login_Pass {
            get {
                return ((string)(this["Login_Pass"]));
            }
            set {
                this["Login_Pass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string Favorites_MAXCOUNT {
            get {
                return ((string)(this["Favorites_MAXCOUNT"]));
            }
            set {
                this["Favorites_MAXCOUNT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Use_Favorites {
            get {
                return ((bool)(this["Use_Favorites"]));
            }
            set {
                this["Use_Favorites"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Use_DefaultMenu {
            get {
                return ((bool)(this["Use_DefaultMenu"]));
            }
            set {
                this["Use_DefaultMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public string SKIN {
            get {
                return ((string)(this["SKIN"]));
            }
            set {
                this["SKIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string Scan_StopBit {
            get {
                return ((string)(this["Scan_StopBit"]));
            }
            set {
                this["Scan_StopBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string Print_ParityBit {
            get {
                return ((string)(this["Print_ParityBit"]));
            }
            set {
                this["Print_ParityBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1004")]
        public string Socket_Port {
            get {
                return ((string)(this["Socket_Port"]));
            }
            set {
                this["Socket_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T")]
        public string Print_CommunicationType {
            get {
                return ((string)(this["Print_CommunicationType"]));
            }
            set {
                this["Print_CommunicationType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Use_TouchMenu {
            get {
                return ((bool)(this["Use_TouchMenu"]));
            }
            set {
                this["Use_TouchMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100.100.100.173")]
        public string WCF_ServiceIP {
            get {
                return ((string)(this["WCF_ServiceIP"]));
            }
            set {
                this["WCF_ServiceIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Print_Name {
            get {
                return ((string)(this["Print_Name"]));
            }
            set {
                this["Print_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LPT1")]
        public string Print_ParallelPortName {
            get {
                return ((string)(this["Print_ParallelPortName"]));
            }
            set {
                this["Print_ParallelPortName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string Print_FlowControl {
            get {
                return ((string)(this["Print_FlowControl"]));
            }
            set {
                this["Print_FlowControl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("172.20.30.242")]
        public string Print_NetworkIPAddress {
            get {
                return ((string)(this["Print_NetworkIPAddress"]));
            }
            set {
                this["Print_NetworkIPAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public string Print_NetworkPort {
            get {
                return ((string)(this["Print_NetworkPort"]));
            }
            set {
                this["Print_NetworkPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public string Print_DPI {
            get {
                return ((string)(this["Print_DPI"]));
            }
            set {
                this["Print_DPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ZPL")]
        public string Print_ProgrammingLanguage {
            get {
                return ((string)(this["Print_ProgrammingLanguage"]));
            }
            set {
                this["Print_ProgrammingLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string Print_Copies {
            get {
                return ((string)(this["Print_Copies"]));
            }
            set {
                this["Print_Copies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string Print_Mirror {
            get {
                return ((string)(this["Print_Mirror"]));
            }
            set {
                this["Print_Mirror"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string Print_Rotate180 {
            get {
                return ((string)(this["Print_Rotate180"]));
            }
            set {
                this["Print_Rotate180"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Print_LabelTop {
            get {
                return ((int)(this["Print_LabelTop"]));
            }
            set {
                this["Print_LabelTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Scan2_Comport {
            get {
                return ((string)(this["Scan2_Comport"]));
            }
            set {
                this["Scan2_Comport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Scan2_BaudRate {
            get {
                return ((string)(this["Scan2_BaudRate"]));
            }
            set {
                this["Scan2_BaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Scan2_DataBit {
            get {
                return ((string)(this["Scan2_DataBit"]));
            }
            set {
                this["Scan2_DataBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Scan2_ParityBit {
            get {
                return ((string)(this["Scan2_ParityBit"]));
            }
            set {
                this["Scan2_ParityBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Scan2_StopBit {
            get {
                return ((string)(this["Scan2_StopBit"]));
            }
            set {
                this["Scan2_StopBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Use_Auto_Login {
            get {
                return ((bool)(this["Use_Auto_Login"]));
            }
            set {
                this["Use_Auto_Login"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AutoLogin_User {
            get {
                return ((string)(this["AutoLogin_User"]));
            }
            set {
                this["AutoLogin_User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TSC TTP-243 Pro")]
        public string TSC_PRINT_NAME {
            get {
                return ((string)(this["TSC_PRINT_NAME"]));
            }
            set {
                this["TSC_PRINT_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NORMAL")]
        public string WINSTYLE {
            get {
                return ((string)(this["WINSTYLE"]));
            }
            set {
                this["WINSTYLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PLANT {
            get {
                return ((string)(this["PLANT"]));
            }
            set {
                this["PLANT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public string Level1 {
            get {
                return ((string)(this["Level1"]));
            }
            set {
                this["Level1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public string Level2 {
            get {
                return ((string)(this["Level2"]));
            }
            set {
                this["Level2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public string Level3 {
            get {
                return ((string)(this["Level3"]));
            }
            set {
                this["Level3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BRD_WORKCTR {
            get {
                return ((string)(this["BRD_WORKCTR"]));
            }
            set {
                this["BRD_WORKCTR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BONDING_LINE {
            get {
                return ((string)(this["BONDING_LINE"]));
            }
            set {
                this["BONDING_LINE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BONDING_UNIT {
            get {
                return ((string)(this["BONDING_UNIT"]));
            }
            set {
                this["BONDING_UNIT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BONDING_PARTNO {
            get {
                return ((string)(this["BONDING_PARTNO"]));
            }
            set {
                this["BONDING_PARTNO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OPER {
            get {
                return ((string)(this["OPER"]));
            }
            set {
                this["OPER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string PassLabel {
            get {
                return ((string)(this["PassLabel"]));
            }
            set {
                this["PassLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string NGLabel {
            get {
                return ((string)(this["NGLabel"]));
            }
            set {
                this["NGLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Scan3_Comport {
            get {
                return ((string)(this["Scan3_Comport"]));
            }
            set {
                this["Scan3_Comport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Scan3_BaudRate {
            get {
                return ((string)(this["Scan3_BaudRate"]));
            }
            set {
                this["Scan3_BaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Scan3_DataBit {
            get {
                return ((string)(this["Scan3_DataBit"]));
            }
            set {
                this["Scan3_DataBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Scan3_ParityBit {
            get {
                return ((string)(this["Scan3_ParityBit"]));
            }
            set {
                this["Scan3_ParityBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Scan3_StopBit {
            get {
                return ((string)(this["Scan3_StopBit"]));
            }
            set {
                this["Scan3_StopBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Scan4_Comport {
            get {
                return ((string)(this["Scan4_Comport"]));
            }
            set {
                this["Scan4_Comport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Scan4_BaudRate {
            get {
                return ((string)(this["Scan4_BaudRate"]));
            }
            set {
                this["Scan4_BaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Scan4_DataBit {
            get {
                return ((string)(this["Scan4_DataBit"]));
            }
            set {
                this["Scan4_DataBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Scan4_ParityBit {
            get {
                return ((string)(this["Scan4_ParityBit"]));
            }
            set {
                this["Scan4_ParityBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Scan4_StopBit {
            get {
                return ((string)(this["Scan4_StopBit"]));
            }
            set {
                this["Scan4_StopBit"] = value;
            }
        }
    }
}
